name: Build binaries

permissions: {}

on:
  workflow_dispatch:
    inputs:
      profile:
        default: "release"
        description: "Build profile"
        type: choice
        options:
          - "release"
          - "dev"

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    name: Build
    runs-on: blacksmith-16vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Build
        run: cargo build --bin tempo-grpc --features "asm-keccak,jemalloc,otlp" --profile ${{ inputs.profile || 'dev' }}
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        id: binary_upload
        with:
          if-no-files-found: "error"
          name: tempo-grpc
          path: target/${{ inputs.profile || 'debug' }}/tempo-grpc
